NUMBER_INTERMEDIATE_STATES = (
    3  # Intermediate states are non-initial/non-terminal states
)
PROBABILITY_DIFFERENT_TRANSITION_AT_LAST_STATE = 0.99

REWARD_EACH_TRANSITION = 1

NUMBER_OF_EPISODES = 10000
N_STEP = 2
GAMMA = 1
ALPHA = 0.001
